### ISSUE TITLE
scrolling up on sub-spaces page, makes it jump in a funny

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1147] opened 2023-11-13 12:28 UTC
Experenced on iOS V16.7.1, iPhone SE 3rd gen
Build: App Store version 1.23.1116/iOS

**Comment by emilvincentz** [comment] 2023-11-13 12:30
https://github.com/acterglobal/a3/assets/77483554/95a47b82-0be4-47f4-b3c6-2e92618b69f7

**Comment by kumarpalsinh25** [comment] 2023-11-21 11:01
@emilvincentz 
Can you check this issue on latest build. Not sure, but may be this is fixed with the issue [#1143 ](https://github.com/acterglobal/a3/issues/1143) as I am not able to reproduce it.

Let me know if it is not fixed then I will check for more details.

**Comment by emilvincentz** [comment] 2023-11-21 11:07
yes, will test when latest nightly for IOS version is up and running✌️

**Comment by emilvincentz** [comment] 2023-11-22 10:43
@kumarpalsinh25 okey just tested it on the latest highly on iOS (iPhone SE 3rd gen).
the issue still persist. but only with many subspaces where you need to scroll down.
the one I tested on has around 10 sub spaces. 
Scrolling down works fine until you get to the bottom, then It starts jumping and also its jumping when scrolling up, but not down

**Comment by kumarpalsinh25** [comment] 2023-11-22 10:45
@emilvincentz,
Thanks for sharing the details. I will now check the details and do the needful.

**Comment by kumarpalsinh25** [comment] 2023-11-23 09:53
@emilvincentz 
Before doing any changes in code, I'm trying to reproduce issue to have better idea on the root cause.

But unfortunately I'm not able to reproduce the issue as described.

I have even tried to on low configuration android device but not able to generate it.

Reference VIdeo:


https://github.com/acterglobal/a3/assets/51526480/d30e67f0-d3a2-4c5d-af90-90309175fa04

**Comment by emilvincentz** [comment] 2023-11-23 10:01
hm very weird.
as you can see it still happens to me, when hitting hitting the button and also scrolling jup (works fine scrolling down)

https://github.com/acterglobal/a3/assets/77483554/c3012d65-733f-4510-b014-4510ad0982e4

I wonder if other variables could be:
- when space description preview text is added
- When there user are not yet part of the subspaces, which means that the "join"  button shows on all sub spaces
- Subspaces have image

if not, then lets pause it for now and see if other users report it as well or if its just me

**Comment by kumarpalsinh25** [comment] 2023-11-23 13:25
@emilvincentz 
Tested again with the given criteria as below and with low configuration Android device. it is working fine. 

1. when space description preview text is added
2. When there user are not yet part of the subspaces, which means that the "join" button shows on all sub spaces
3. Subspaces have image

Reference Video:
https://github.com/acterglobal/a3/assets/51526480/57442807-bd06-47bd-a921-9b77b6e437dd

Not sure if this is device-specific and/or user-specific and/or space-specific.

**Comment by emilvincentz** [comment] 2023-11-23 13:30
Well done testing it. 
Let's wait and see then what users say. For now we can close / park this one.

Maybe a last try, is that i actually invite you to the WeRise space where we it happens (the sub spaces under we rise) 
Look out for an invite

**Comment by kumarpalsinh25** [comment] 2023-11-29 05:01
@gnunicorn 
have you also faced this?

https://github.com/acterglobal/a3/issues/1147#issuecomment-1829791807

**Closed** 2023-12-11 12:35 UTC
Labels: bug, smooth UX
