### ISSUE TITLE
DM chat creation stall indefinitely.

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1130] opened 2023-11-07 12:55 UTC
When i create DM, its stuck on loading. 
However on element i can see that the DM has been succefully created. 

https://github.com/acterglobal/a3/assets/77483554/41548ce4-c071-40e6-bb4a-24f9215258a7

**Comment by kumarpalsinh25** [comment] 2023-11-24 12:25
@emilvincentz 
Just tested this and created 2-3 DMs but not able to reproduce above issue.

Is there any specific use-case in which I have to test to reproduce it?

**Comment by kumarpalsinh25** [comment] 2023-11-27 07:50
@emilvincentz 
We can close this issue if it is fixed.

**Comment by emilvincentz** [comment] 2023-11-27 07:56
sounds good

**Closed** 2023-11-27 07:56 UTC
Labels: bug, t-ios
