### ISSUE TITLE
Synapse's system msg is not parsed properly

### ISSUE THREAD

**Issue by bitfriend** [acterglobal/a3#2136] opened 2024-09-03 10:05 UTC
![image](https://github.com/user-attachments/assets/069f1810-b9d9-4f94-8e70-73221e6d5464)
I remember I wrote code for system msg before.
But some bug may exist somewhere.

**Comment by gnunicorn** [comment] 2024-09-03 10:07
duplicate of https://github.com/acterglobal/a3/issues/1907 .

**Closed by gnunicorn** 2024-09-03 10:07 UTC
Labels: bug, flutter
