### ISSUE TITLE
Error when sending message

### ISSUE THREAD

**Issue by emilvincentz** [acterglobal/a3#1544] opened 2024-03-25 10:13 UTC
When i click "send" it just looks like this.

![Image](https://github.com/acterglobal/a3/assets/77483554/dad77818-b33d-4ba9-bd55-157948ce0562)

**Comment by kumarpalsinh25** [comment] 2024-03-27 11:22
@emilvincentz 
Is this random thing or specific scenario?

**Comment by emilvincentz** [comment] 2024-03-27 11:25
More Random.
But if I had to make a guess,it could maybe be when the server is down or r something?

**Comment by kumarpalsinh25** [comment] 2024-04-12 07:14
@emilvincentz 
Is this issue is still there?

Probably it will be fixed with https://github.com/acterglobal/a3/pull/1591

**Comment by kumarpalsinh25** [comment] 2024-04-12 10:47
Ok perfect then can we close this as it is fixed by https://github.com/acterglobal/a3/pull/1591.

Feel free to reopen it if face this issue again.

**Comment by emilvincentz** [comment] 2024-04-12 12:39
Sorry as reported today in a3-meta this actually still perisists, but not consistent

**Comment by gnunicorn** [comment] 2024-04-29 09:36
seems to be related to connectivity issues.

**Comment by gtalha07** [comment] 2024-04-30 10:38
> seems to be related to connectivity issues.
@emilvincentz @gnunicorn 
Been able to reproduce this, this creates hanging state for controller upon trying to send with no internet. We can show error UI here or do we need some retry mechanism upon restoring???

**Comment by gnunicorn** [comment] 2024-04-30 11:07
@gtalha07 there is a retry-mechanism in rust but it seems that under certain circumstances it needs too long and we have no clear UI for that in-between ....

**Comment by gtalha07** [comment] 2024-05-06 16:35
RE-opening as it seems the connectivity alone cannot determine internet/server reachable state.

**Closed** 2024-05-27 09:23 UTC
